spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portifoliodb}?stringtype=unspecified
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type=VARCHAR

jwt.secret=MinhaChaveSuperSecreta2026SosArtistas
jwt.expiration=86400000
